### ISSUE TITLE
Fofix error: OpenGL not available

### ISSUE THREAD

**Issue by wonx** [zerojay/RetroPie-Extra#307]
I tried installing fofix in my rpi3 retropie machine. I started by running the RetroPie-Extra script and then installing fofix in retropie-config. Apparently, it went well.

Now I want to start it, from the command line (I don't see any menu entry in emulationstation), and I get the following errors:

```
[    0.002720] (D) Logging initialized: Mon Sep 17 22:08:51 2018
[    4.338336] (W) Pitch bending is not supported; install john.stumpo's pitchbend module (r7 or higher) if you want it.
[    7.060725] (D) GameEngine class init (GameEngine.py)...
[    7.060922] (D) FoFiX v3.121 Final starting up...
[    7.060976] (D) pygame version: 1.9.2a0
[    7.065261] (D) Initializing audio.
[    7.097291] (D) Audio configuration: (44100, -16, 2)
[    7.291799] (D) Initializing pygame.mixer & audio system at 44100 Hz.
[    7.291940] (D) Initializing video.
[    7.399941] (W) Video setup failed. Trying without antialiasing.
[    7.401075] (E) Video setup failed. Make sure your graphics card supports 32-bit display modes.
Traceback (most recent call last):
  File "/usr/share/fofix/src/Video.py", line 168, in multisampleReset
    self.screen = pygame.display.set_mode(resolution, self.flags)
error: OpenGL not available

[    7.403570] (E) Terminating due to unhandled exception:
Traceback (most recent call last):
  File "FoFiX.py", line 276, in <module>
    main()
  File "FoFiX.py", line 175, in main
    engine = GameEngine(config)
  File "/usr/share/fofix/src/GameEngine.py", line 550, in __init__
    self.video.setMode((width, height), fullscreen = fullscreen, multisamples = multisamples)
  File "/usr/share/fofix/src/Video.py", line 82, in setMode
    self.multisampleReset(resolution)
  File "/usr/share/fofix/src/Video.py", line 173, in multisampleReset
    self.screenError()
  File "/usr/share/fofix/src/Video.py", line 168, in multisampleReset
    self.screen = pygame.display.set_mode(resolution, self.flags)
error: OpenGL not available

```

So I tried installing the experimental OpenGL drivers and it almost crashed my whole system (it kept rebooting and showing nothing on the screen), so I disabled it.

Is this a known issue? Should I have done something differently?

Thanks in advance.

**Comment by symbios24** [comment]
fofix should be in the ports section in retropie and not in a menu entry it self.plus fofix is not working anymore,try it in retropie 4.3

**Comment by symbios24** [comment]
fofix should be in the ports section in retropie and not in a menu entry it self.
plus fofix is not working anymore,try it in an older retropie with jessie core.

**Comment by wonx** [comment]
Oh, ok, I didn't look in the ports section.

Any plans on making it work again? I am using jessie, by the way.

**Comment by symbios24** [comment]
There is a list of non working games since jessie im waiting for zerojay to fix them some time now

**Comment by symbios24** [comment]
Try it in Strech but its not going to work there also,There is a list of non working games since jessie im waiting for zerojay to fix them some time now

**Comment by zerojay** [comment]
I would love to have these fixed but I don't know how to do so. Someone else is going to have to figure it out because I've banged my head on it so so many times for so very long and have gotten nowhere.

**Comment by symbios24** [comment]
no worries we will figure it out one day :)

**Comment by symbios24** [comment]
There is a solution for Openxcom i just did not figure out how to add it to the script etc.

https://github.com/zerojay/RetroPie-Extra/issues/288#issuecomment-410974735

**Comment by symbios24** [comment]
There is a solution for Openxcom i just did not figure out how to add it to the script etc.

#288 (comment)

when you have time you can add it.

**Comment by zerojay** [comment]
FoFix is no longer a part of Raspbian in buster, so this will require a rewrite of the scriptmodule to get working again.
